### ISSUE TITLE
Unable to download teh dataset.

### ISSUE THREAD

**Issue by ashishmithole** [marcocor/smaph#1]
https://groviera1.di.unipi.it:5001/sharing/RBHB0Yxz5 is not working. Is there any other way to get the dataset?

**Comment by marcocor** [comment]
Hi, that is a temporary location but the link seems alright. You have to browse there and accept any SSL certificate, just make sure to verify the MD5 checksum of the unzipped files. I will move the datasets to datahub as soon as they activate my account. Let me know if you encounter any other issue.

**Comment by ashishmithole** [comment]
Thanks for the reply.

Yes. The link is fine. There seems to be some permission issue from my side in using HTTPS on 5001 port.  My bad.
