### ISSUE TITLE
Quality issues

### ISSUE THREAD

**Issue by daltonj** [marcocor/smaph#2]
Let me know if there is a better place to report issues.

I'm using the REST api and I'm seeing some quality problems:

Cognitive Services pricing—Bing Search API
q=In+England - {"response-code":"OK","annotator":"Smaph annotator - greedy, GOOGLE_CSE","annotations":[]}
Support of GM crops	{"response-code":"OK","annotator":"Smaph annotator - greedy, GOOGLE_CSE","annotations":[]}

Others are more arguably recall issues:
History of study	{"response-code":"OK","annotator":"Smaph annotator - greedy, GOOGLE_CSE","annotations":[]}
Medical	{"response-code":"OK","annotator":"Smaph annotator - greedy, GOOGLE_CSE","annotations":[]}

In particular, most of these are recall losses.  Are there parameters that would result in more effective tagging?

**Comment by marcocor** [comment]
Hi Jeff,
SMAPH is trained with the objective function of maximizing the average F1 across queries. For this reason, it can be somewhat conservative when it comes to choosing which annotations to keep and which to discard. SMAPH-3, the most performing algorithm, chooses annotations in cascade, making it impossible to simply decrease the threshold of annotation quality. The correct way to increase recall (at the cost of a lower precision and F1) would be to tweak the training process and have it maximize not F1 but rather F-beta with beta>1. In fact,[ F1 is an instance of a more general F-beta function](https://en.wikipedia.org/wiki/F1_score) where the beta parameter decides whether to weight recall more (beta>1) or less (beta<1) than precision.

Probably, to include the annotations that have been taken into consideration by smaph and later discarded, one can use the [debug](https://github.com/marcocor/smaph/blob/master/src/main/java/it/unipi/di/acube/smaph/servlet/SmaphServlet.java#L61) interface.

**Comment by daltonj** [comment]
So, the answer here is there is no way to change the settings to improve recall?  This significantly limits my ability to use this for research.  Shall I open a new issue to make some of these configurable?

**Comment by marcocor** [comment]
Did you try the /debug interface? That should include entities that got a score lower than the threshold.
Which version of SMAPH (1, -S, or 3) would you like to adjust recall for?
