### ISSUE TITLE
Query of death

### ISSUE THREAD

**Issue by daltonj** [marcocor/smaph#3]
The query: q=Second+atmosphere consistently returns a 500 response. 
HTTP/1.1 500 Internal Server Error [Server: nginx, Date: Tue, 15 May 2018 14:37:03 GMT, Content-Type: text/html;charset=utf-8, Content-Length: 1633, Connection: keep-alive, Content-Language: en] org.apache.http.conn.BasicManagedEntity@2b5825fa

All other queries have been fine.

**Comment by marcocor** [comment]
Hello, thanks for reporting this issue. It has been fixed with commit 99be1cf. A new version of SMAPH built from that commit has been deployed on D4Science.
